### ISSUE TITLE
2주차 과제: (2) 백준 20207 달력

### ISSUE THREAD

**Issue by jungyoonoh** [jungyoonoh/unit-study#10]
https://www.acmicpc.net/problem/20207
달력 문제를 풀어주세요

**Comment by Seon-Ju** [comment]
https://github.com/Seon-Ju/unit-study/commit/fae1b84aaf973980c48afa01d6089f2b2f190eab

삽질 x 1000000......
나가봐야 해서 풀이방법 이따 추가하겠읍니다

**Comment by SoominRyu** [comment]
https://github.com/SoominRyu/unit-study/blob/main/Soomin/Baekjoon/Implementation/20207%20%EB%8B%AC%EB%A0%A5.py

1. 해당 날짜에 일정이 몇 번 있는지 [0]*365 리스트에서 체크
2. 일정 없는 날 만나기 전까지의 (날짜 수=가로) * (가장 일정이 많은 날 일정 개수=세로)를 hap에 더해줌
3. 1일 ~ 365일 매일 일정이 있는 경우, 365일에 일정이 있는 경우 예외 처리

* 처음에 달력 빨간색처럼 구하고 코딩지 붙이는 건 줄 알고^^^ 코드 다 짜고 나서 코딩지 어떻게 붙이지 고민하다가 빨간 부분 색칠을 굳이 안 해도 된다를 깨달아버렸음 ༎ຶ‿༎ຶ

**Comment by jungyoonoh** [comment]
https://github.com/jungyoonoh/unit-study/blob/main/Yoonoh/Baekjoon/Implementation/20207_%EB%8B%AC%EB%A0%A5.py

1. 달력의 일정 시작과 끝 지점을 표시한다
2. 이를 누적합으로 나타낸다
3. 누적합이 첫 양수인 부분은 시작, 이후 첫 음수 or 0인 지점이 끝지점으로 리스트 슬라이싱 후 최댓값 구해서 사각형 만들어서 더하기
