### ISSUE TITLE
4주차 과제: (1) 백준 16926 배열 돌리기 1

### ISSUE THREAD

**Issue by jungyoonoh** [jungyoonoh/unit-study#15]
https://www.acmicpc.net/problem/16926
배열 돌리기 1 문제를 풀어주세요

**Comment by jungyoonoh** [comment]
https://github.com/jungyoonoh/unit-study/blob/c18ceac58e927e5026a33731083f5dafed2cf621/Yoonoh/Baekjoon/Implementation/16926_%EB%B0%B0%EC%97%B4_%EB%8F%8C%EB%A6%AC%EA%B8%B0_1.py

1. 기준값을 한군데 잡고 4면의 데이터를 시계방향 순으로 한칸씩 이동한다 (반시계로 돌려야하므로)
2. 사각형 내부를 돌리기 위해 전체 사각형의 중앙값 이전까지만 기준값을 설정한다

**Comment by SoominRyu** [comment]
https://github.com/SoominRyu/unit-study/blob/main/Soomin/Baekjoon/Implementation/16926%20%EB%B0%B0%EC%97%B4%20%EB%8F%8C%EB%A6%AC%EA%B8%B01.py

1. → ↓ ← ↑ 순서로 리스트에 담아줌 
2. r만큼 회전 반복 리스트
3. → ↓ ← ↑ 순서로 다시 회전된 리스트 넣음

**Comment by Seon-Ju** [comment]
https://github.com/Seon-Ju/unit-study/blob/main/Seonju/Baekjoon/Implementation/16926_%EB%B0%B0%EC%97%B4%20%EB%8F%8C%EB%A6%AC%EA%B8%B0%201.py

1. 사각형의 가장 왼쪽 위 지점을 start라 하고 start=0인 바깥쪽 사각형부터 회전시킨다. graph는 회전시키기 전의 리스트, graph_new는 이 graph를 회전시킨 결과 리스트다.
2. 이 1회전을 r번 반복시킨다.
