### ISSUE TITLE
5주차 과제: (1) 프로그래머스 - 거리두기 확인하기 

### ISSUE THREAD

**Issue by jungyoonoh** [jungyoonoh/unit-study#19]
https://programmers.co.kr/learn/courses/30/lessons/81302

**Comment by SoominRyu** [comment]
https://github.com/SoominRyu/unit-study/blob/main/Soomin/Programmers/%EA%B1%B0%EB%A6%AC%EB%91%90%EA%B8%B0%20%ED%99%95%EC%9D%B8%ED%95%98%EA%B8%B0.py

1. 방 하나 당 자리 한 자리씩 나눠서 리스트에 넣음
2. 사람이 앉아 있는 곳 리스트에 담기
3. P 위치 중 맨해튼 거리가 지켜지지 않은 위치 리스트에 넣음
4. 맨해튼 거리가 지켜지지 않은 위치 중 X 파티션이 있는 곳 체크 (대각선 경우 추가 조건)

**Comment by jungyoonoh** [comment]
https://github.com/jungyoonoh/unit-study/blob/main/Yoonoh/Programmers/Kakao/%EA%B1%B0%EB%A6%AC%EB%91%90%EA%B8%B0_%ED%99%95%EC%9D%B8%ED%95%98%EA%B8%B0.py

1. 5x5에서 맨해튼 거리가 1인 곳과 2인 곳을 각각 벡터로 나타낸다
2. 사람이 앉은 곳만 탐색한다
3. 맨해튼 거리가 1인곳에는 당연히 사람이 없어야하고, 2인곳에는 파티션이 있는지 확인한다
4. 모든 조건을 만족하면 1, 하나라도 불만족시 0 반환

**Comment by Seon-Ju** [comment]
https://github.com/Seon-Ju/unit-study/blob/main/Seonju/Programmers/Implementation/%EA%B1%B0%EB%A6%AC%EB%91%90%EA%B8%B0%20%ED%99%95%EC%9D%B8%ED%95%98%EA%B8%B0.py

1. P의 위치를 (x, y) 튜플로 저장하는 리스트 생성
2. combinations로 두 P의 위치를 조합
3. 조합을 탐색하면서 두 P 사이 거리를 계산하고, 거리가 2 이하라면 중간에 파티션이 있는지 검사
4. 파티션이 없다면 0, 있다면 1
