### ISSUE TITLE
6주차 과제: (1) 백준 9655 돌 게임

### ISSUE THREAD

**Issue by jungyoonoh** [jungyoonoh/unit-study#25]
돌 게임을 풀어주세요
https://www.acmicpc.net/problem/9655

Optional) 
돌 게임 3을 풀어주세요
https://www.acmicpc.net/problem/9657

**Comment by Seon-Ju** [comment]
https://github.com/Seon-Ju/unit-study/blob/main/Seonju/Baekjoon/Dynamic%20Programming/9655_%EB%8F%8C%20%EA%B2%8C%EC%9E%84.py

간단히 테스트케이스 몇 개 그려보면 돌이 짝수개일 때 상근이가, 홀수개일 때 창영이가 이긴다는 규칙을 발견할 수 있음
이걸 DP로는 어떻게 풀어야 할지 모르겠음

**Comment by jungyoonoh** [comment]
돌게임은 홀수일때 상근이 승 짝수일때 창영이 승
https://github.com/jungyoonoh/unit-study/blob/main/Yoonoh/Baekjoon/DP/9655_%EB%8F%8C_%EA%B2%8C%EC%9E%84.py

돌게임3은 가장 마지막 턴의 직전턴(가능한 경우의 수)을 입장 바꿔 생각하면 된다. 
직전턴에 1개를 놓던 3개를 놓던 4개를 놓던 본인 차례였을때 이겼다면 현재 턴에서는 반드시 패배한다.
https://github.com/jungyoonoh/unit-study/blob/main/Yoonoh/Baekjoon/DP/9657_%EB%8F%8C_%EA%B2%8C%EC%9E%843.py

**Comment by SoominRyu** [comment]
https://github.com/SoominRyu/unit-study/blob/main/Soomin/Baekjoon/Dynamic%20Programming/9655%20%EB%8F%8C%20%EA%B2%8C%EC%9E%84.py

돌 개수
짝수 : 상근 승
홀수 : 창영 승 

돌 개수만 체크하면 된다.
dp.... 모르겠음
