### ISSUE TITLE
7주차 과제: (2) 백준 2285 우체국

### ISSUE THREAD

**Issue by jungyoonoh** [jungyoonoh/unit-study#29]
https://www.acmicpc.net/problem/2285
우체국을 풀어주세요

**Comment by SoominRyu** [comment]
https://github.com/SoominRyu/unit-study/blob/main/Soomin/Baekjoon/Greedy/2285%20%EC%9A%B0%EC%B2%B4%EA%B5%AD.py

마을까지의 거리 합이 아닌 각 사람까지 거리의 합임에 유의 <- 여기가 포인트 (?)
몇 가지 케이스 생각해보면 우체국 위치는 사람 수가 중간인 지점에 존재하는 것이 BEST

1. n개 마을 전체 사람 수(people) 체크
2. 마을 번호 순으로 정렬
3. 1번 마을부터 사람 수 합해서 people/2 를 넘는 순간 체크 - 여기가 우체국 위치

**Comment by jungyoonoh** [comment]
https://github.com/jungyoonoh/unit-study/blob/main/Yoonoh/Baekjoon/Greedy/2285_%EC%9A%B0%EC%B2%B4%EA%B5%AD.py

누적합의 중간값을 포함하는 index를 이분탐색으로 찾고 마을 번호 출력하기

**Comment by Seon-Ju** [comment]
https://github.com/Seon-Ju/unit-study/blob/main/Seonju/Baekjoon/Greedy/2285_%EC%9A%B0%EC%B2%B4%EA%B5%AD.py

전체 사람 수를 구하고 마을을 순서대로 탐색하다가 전체 사람 수의 절반을 넘어설 때 해당 마을에 우체국 세우면 됨
✅ 완료
