### ISSUE TITLE
8주차 과제: (1) 백준 21921 블로그

### ISSUE THREAD

**Issue by jungyoonoh** [jungyoonoh/unit-study#31]
블로그 문제를 풀어주세요
https://www.acmicpc.net/problem/21921

**Comment by Seon-Ju** [comment]
https://github.com/Seon-Ju/unit-study/blob/main/Seonju/Baekjoon/Two%20Pointer/21921_%EB%B8%94%EB%A1%9C%EA%B7%B8.py

start, end 포인터 설정해서 start부터 end까지의 합인 summary가 maximum보다 작으면 end를 한 칸 뒤로 옮겨서 다시 합을 구함
투포인터 감이 잡히는 것 같긴 한데 이건 구간합으로 푸는 게 더 효율적일 것 같다!

**Comment by jungyoonoh** [comment]
https://github.com/jungyoonoh/unit-study/blob/main/Yoonoh/Baekjoon/TwoPointer/21921_%EB%B8%94%EB%A1%9C%EA%B7%B8.py

range가 고정되어있어서 누적합 + 슬라이딩 윈도우 형태로 해결
a가 일별 블로그 방문자수, S가 a의 누적합이라고 할 때 구간 t의 합의 구간합은 Sn - Sn-t이다.
단 n = t일경우 an = Sn이므로 예외처리

**Comment by SoominRyu** [comment]
https://github.com/SoominRyu/unit-study/blob/main/Soomin/Baekjoon/Two%20Pointer/21921%20%EB%B8%94%EB%A1%9C%EA%B7%B8.py

for문으로 x개씩 start, end 지점 찾아서 슬라이싱 해서 풀었더니 시간초과
accumulate 누적합 사용
