### ISSUE TITLE
9주차 과제: (1) 백준 15961 회전초밥

### ISSUE THREAD

**Issue by jungyoonoh** [jungyoonoh/unit-study#37]
https://www.acmicpc.net/problem/15961
회전초밥을 풀어주세요

**Comment by Seon-Ju** [comment]
https://github.com/Seon-Ju/unit-study/blob/main/Seonju/Baekjoon/Two%20Pointer/15961_%ED%9A%8C%EC%A0%84%20%EC%B4%88%EB%B0%A5.py

먹는 갯수 k개가 고정이므로 start 포인터와 end 포인터는 뒤로 한 칸씩 함께 이동한다.
초밥 리스트가 처음과 끝이 연결돼 원형을 이루기 때문에 인덱싱을 할 때 인덱스에 %n을 추가해줘야 한다.

처음 시작할 때만 k개를 먹는 for문을 돌고, 그 이후부터는 start쪽 초밥 한 개를 빼주고 end쪽 초밥 한 개를 더해주는 식으로 탐색을 진행하다가 먹은 k개 중 쿠폰넘버 초밥이 있는지에 따라 경우를 나눠 최댓값을 갱신한다.

**Comment by jungyoonoh** [comment]
https://github.com/jungyoonoh/unit-study/blob/main/Yoonoh/Baekjoon/TwoPointer/15961_%ED%9A%8C%EC%A0%84%EC%B4%88%EB%B0%A5.py

### 솔루션
투포인터로 해결, 데이터를 defaultdict에 저장.
현재 초밥을 먹으면, 이전에 먹은 초밥 정보를 제거하는 형태로 수행

### 시행착오
1. 중복 여부를 처음에 set으로 판단했다가 이전에 먹은 초밥을 제거했는데 중간에 같은 index가 있을 경우 제거할 필요가 없으나 제거를 수행하게됨
2. list로 데이터 수집 후 set으로 변환 시도했으나 시간복잡도 O(N)으로 300만 x 3천으로 시간초과

✔️ 완료

**Comment by SoominRyu** [comment]
https://github.com/SoominRyu/unit-study/blob/main/Soomin/Baekjoon/Two%20Pointer/15961%20%ED%9A%8C%EC%A0%84%20%EC%B4%88%EB%B0%A5.py

약간 dp 처럼 풀었음
1. d번까지 번호 만들고 개수 0개로 채움 (eat)
2. 쿠폰은 무조건 사용한다
3. 첫 연속 k개 체크  (이미 먹은 적 있는 번호 - eat만 카운트 증가 / 먹은 적 없는 번호 - eat과 전체 합 증가)
4. 제일 앞 빼고, 뒤에 하나 추가하면서 최대 찾기

✅ 완료
