### ISSUE TITLE
9주차 과제: (2) 백준 4179 불!

### ISSUE THREAD

**Issue by jungyoonoh** [jungyoonoh/unit-study#38]
https://www.acmicpc.net/problem/4179
불! 문제를 풀어주세요

**Comment by Seon-Ju** [comment]
https://github.com/Seon-Ju/unit-study/blob/main/Seonju/Baekjoon/Graph%20Traversal/4179_%EB%B6%88!.py

이동하는 대상인 지훈이와 불을 큐에 넣고 BFS 진행!
단, 어느 타임이든 지훈이를 먼저 이동시켜야 하기 때문에 지훈이의 위치를 큐에 가장 먼저 넣어줌으로써 이를 달성한다.

지훈이의 탈출 시간을 출력해야 해서 큐에는 위치와 함께 시간 정보도 넣어준다. (불의 시간은 고려 대상 X → -1로 넣어줌)

**Comment by jungyoonoh** [comment]
https://github.com/jungyoonoh/unit-study/blob/main/Yoonoh/Baekjoon/GraphTraversal/4179_%EB%B6%88.py

BFS로 풀이, 지훈이 먼저 이동 -> 불 이동의 순서로 진행한다
불이 번지고 난 자리는 벽으로 이동불가 처리를 해주고, 지훈이의 이동은 isVisited로 체크해준다
지훈이의 이동 차례에 현재 위치가 불로 덮이지 않았을 때 외곽에 있다면 탈출 성공

**Comment by SoominRyu** [comment]
https://replit.com/@SoominRyu/codingtest#%EB%B6%88!.py

일부 케이스 통과 못해서 커밋 안 함....
가장자리 판단 기준에서 틀린 것으로 추정
