### ISSUE TITLE
10주차 과제: (1) 백준 17129 윌리암슨수액빨이딱따구리가 정보섬에 올라온 이유

### ISSUE THREAD

**Issue by jungyoonoh** [jungyoonoh/unit-study#41]
https://www.acmicpc.net/problem/17129
윌리암슨수액빨이딱따구리가 정보섬에 올라온 이유를 풀어주세요

**Comment by jungyoonoh** [comment]
BFS로 풀었습니다
2를 기준으로 3,4,5중에 가장 먼저 찾는 녀석의 거리를 출력하고 종료
탐색이 완료되었을 때 아무것도 찾지 못했다면 NIE

✅ 완료

**Comment by Seon-Ju** [comment]
https://github.com/Seon-Ju/unit-study/blob/main/Seonju/Baekjoon/Graph%20Traversal/17129_%EC%9C%8C%EB%A6%AC%EC%95%94%EC%8A%A8%EC%88%98%EC%95%A1%EB%B9%A8%EC%9D%B4%EB%94%B1%EB%94%B0%EA%B5%AC%EB%A6%AC%EA%B0%80%20%EC%A0%95%EB%B3%B4%EC%84%AC%EC%97%90%20%EC%98%AC%EB%9D%BC%EC%98%A8%20%EC%9D%B4%EC%9C%A0.py

그래프 형태를 입력받으면서 동시에 2의 위치를 x, y에 저장하고 그 위치에서 BFS를 시작
동서남북 네 방향의 숫자를 보고 [3, 4, 5] 안에 있는 값이라면 출력하고 종료

✅ 완료

**Comment by SoominRyu** [comment]
https://github.com/SoominRyu/unit-study/blob/main/Soomin/Baekjoon/Graph%20Traversal/17129%20%EC%9C%8C%EB%A6%AC%EC%95%94%EC%8A%A8%EC%88%98%EC%95%A1%EB%B9%A8%EC%9D%B4%EB%94%B1%EB%94%B0%EA%B5%AC%EB%A6%AC%EA%B0%80%20%EC%A0%95%EB%B3%B4%EC%84%AC%EC%97%90%20%EC%98%AC%EB%9D%BC%EC%98%A8%20%EC%9D%B4%EC%9C%A0.py

BFS
2 위치에서 시작
0 만나면 visited에 움직인 거리를 저장
3,4,5 만나면 그 전까지 visited에 저장된 거리 출력하고 종료
다 돌 때까지 종료 못했으면 NIE 출력

✅ 완료
