### ISSUE TITLE
12주차 과제: (1) 백준 15724 주지수

### ISSUE THREAD

**Issue by jungyoonoh** [jungyoonoh/unit-study#47]
https://www.acmicpc.net/problem/15724
주지수 문제를 풀어주세요

**Comment by jungyoonoh** [comment]
https://github.com/jungyoonoh/unit-study/blob/main/Yoonoh/Baekjoon/DP/15724_%EC%A3%BC%EC%A7%80%EC%88%98.py

1. 2차원 누적합 배열을 만든다. 
2. 좌상단 ~ 우하단 좌표의 사각형의 영역에 대한 누적합을 구한다. 단, 시작점이 0행 혹은 0열인 경우 예외처리가 필요.

✅ 완료

**Comment by Seon-Ju** [comment]
https://github.com/Seon-Ju/unit-study/blob/main/Seonju/Baekjoon/Dynamic%20Programming/15724_%EC%A3%BC%EC%A7%80%EC%88%98.py

**Comment by SoominRyu** [comment]
https://github.com/SoominRyu/unit-study/blob/main/Soomin/Baekjoon/Dynamic%20Programming/15724%20%EC%A3%BC%EC%A7%80%EC%88%98.py

1. 각 행 별로 dp에 합 누적
2. 범위(1 1 3 2 -> a, b, c, d) a ~ c 행까지 반복, box[a][d] ~ box[c][d]까지 더하고, box[a][b-1] ~ box[c][b-1] 빼줌
*accumulate 이용하면 시간 초과 ㅠ

✅ 완료
