### ISSUE TITLE
1주차 과제: (1) 백준 1913 달팽이

### ISSUE THREAD

**Issue by jungyoonoh** [jungyoonoh/unit-study#5]
달팽이 문제를 풀고 공유해주세요
https://www.acmicpc.net/problem/1913

**Comment by jungyoonoh** [comment]
https://github.com/jungyoonoh/unit-study/blob/main/Yoonoh/Baekjoon/Implementation/1913_%EB%8B%AC%ED%8C%BD%EC%9D%B4.py

1. 2부터 시작 & (0,0)에서 종료
2. 짝수번마다 이동횟수 증가
3. 1을 찾는 경우 예외처리

**Comment by Seon-Ju** [comment]
https://github.com/Seon-Ju/unit-study/blob/main/Seonju/Baekjoon/Implementation/1913_%EB%8B%AC%ED%8C%BD%EC%9D%B4.py

이동 순서(우-하-좌-상)가 반복되며 사각형 하나가 채워지기까지 이동 횟수가 상하좌우 각각 n, n- 1, n- 1, n- 2임에 착안해서 상하좌우 cnt를 변수로 두고 한 번 이동할 때마다 해당 방향의 cnt를 1씩 줄임
(0, 0)에 도달하면 종료

**Comment by SoominRyu** [comment]
https://github.com/SoominRyu/unit-study/blob/main/Soomin/Baekjoon/Implementation/1913%20%EB%8B%AC%ED%8C%BD%EC%9D%B4.py

* 답은 나오는데 백준 사이트에서 시간 초과 남 ㅜ --> 코드 줄일 수 있는 방법은 아직 잘 모르겠음 

1. (0,0)부터 시작,  x,y 방향에 따라 값 채워짐
2. 범위를 벗어나거나 이미 채워진 경우 방향 전환(change 변수)
3. n*n+(2*n-2) 번 반복하면 종료 (change가 총 2*n-2 번만큼 일어남, 그만큼 더 반복해 줌)
